version: '2'

networks:
  test_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.1.1.0/24
        gateway: 10.1.1.1

services:
  salt:
    hostname: salt
    image: local:salt-master
    privileged: true
    ports:
    - "5405:5405"
    - "5406:5406"
    volumes:
     - "/Users/ian/src/docker/salt-docker/test-salt:/srv/salt"
     - "/Users/ian/src/docker/salt-docker/test-pillar:/srv/pillar"
    networks:
      test_net:
        ipv4_address: 10.1.1.2
    environment:
    - "TZ=Europe/London"
  dt-box-01:
    hostname: dt-box-01
    image: local:salt-minion
    privileged: true
    ports:
    - "443:443"
    links:
    - salt
    volumes:
     - "/Users/ian/src/docker/salt-docker/test.grains:/etc/salt/grains"
     - "/Users/ian/src/docker/salt-docker/resolv.conf:/etc/resolv.conf"
     - "/Users/ian/src/docker/salt-docker/hosts:/etc/hosts"
    networks:
      test_net:
        ipv4_address: 10.1.1.3
    environment:
    - "TZ=Europe/London"
